version: "3.1"

services: 
    node:
        build: .
        ports: 
            - 3000:3000
        volumes: 
            - .:/app
    mongoserver:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
