version: "3.1"

services: 
    node:
        build: .
        image: youssefsiam38/node
        ports: 
            - 3000:3000
        volumes: 
            - .:/app
    mongo:
        image: mongo
        restart: always
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8080:8081